# Generated by Django 2.0.4 on 2018-04-16 19:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField()),
                ('tier', models.CharField(max_length=50)),
                ('full_name', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='MaintenanceEvent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('imminent', 'Pending: notify users downtime is imminent.'), ('in_progress', 'In Progress: maintenance underway.'), ('completed', 'Completed: maintenance completed.'), ('canceled', 'Canceled: maintenance event did not take place.')], default='imminent', max_length=50)),
                ('scheduled_start', models.DateTimeField(blank=True, null=True)),
                ('scheduled_end', models.DateTimeField(blank=True, null=True)),
                ('started', models.DateTimeField(blank=True, null=True)),
                ('ended', models.DateTimeField(blank=True, null=True)),
                ('reason', models.TextField(blank=True, null=True)),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lil_notification.Application')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='application',
            unique_together={('slug', 'tier')},
        ),
    ]
