# Generated by Django 2.0.4 on 2018-04-18 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lil_notification', '0002_auto_20180418_0125'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalmaintenanceevent',
            name='status',
            field=models.CharField(choices=[('imminent', 'imminent'), ('in_progress', 'in_progress'), ('completed', 'completed'), ('canceled', 'canceled')], default='imminent', max_length=50),
        ),
        migrations.AlterField(
            model_name='maintenanceevent',
            name='status',
            field=models.CharField(choices=[('imminent', 'imminent'), ('in_progress', 'in_progress'), ('completed', 'completed'), ('canceled', 'canceled')], default='imminent', max_length=50),
        ),
    ]
