# Generated by Django 2.0.4 on 2018-04-18 21:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lil_notification', '0003_auto_20180418_1641'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='application',
            name='full_name',
        ),
    ]
